const items = [
    {
        id: '001',
        image: 'images/1.jpg',
        company: 'Espresso Shot',
        item_name: 'Bold, pure coffee to wake up your senses.',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: '',
        delivery_date: '30 Min',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images/2.jpg',
        company: 'Cappuccino Bliss',
        item_name: ' A smooth blend of espresso, steamed milk, and foam.',
        original_price: 599,
        current_price: 507,
        discount_percentage: 12,
        return_period: '',
        delivery_date: '30 Min',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/3.jpg',
        company: 'Americano Classic',
        item_name: ' Espresso with hot water, simple and strong.',
        original_price: 599,
        current_price: 395,
        discount_percentage: 27,
        return_period: '',
        delivery_date: '30 Min',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/4.jpg',
        company: 'Caramel Whisper',
        item_name: ' Velvety latte with hints of caramel syrup.',
        original_price: 499,
        current_price: 499,
        discount_percentage: 0,
        return_period: '',
        delivery_date: '30 Min',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/5.jpg',
        company: 'Vanilla Cloud',
        item_name: ' Light vanilla-infused coffee topped with fluffy foam',
        original_price: 399,
        current_price: 289,
        discount_percentage: 15,
        return_period: '',
        delivery_date: '30 Min',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/6.jpg',
        company: 'Hazelnut Hug',
        item_name: 'A cozy mix of hazelnut and espresso goodness',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: '',
        delivery_date: '30 Min',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'images/7.jpg',
        company: 'Spiced Cinnamon Latte',
        item_name: ' Seasonal warmth with a spicy twist.',
        original_price: 599,
        current_price: 249,
        discount_percentage: 60,
        return_period: '',
        delivery_date: '30 Min',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/8.jpg',
        company: 'Mocha Magic',
        item_name: ' Chocolate meets coffee in this rich, sweet favorite.',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: '',
        delivery_date: '30 Min',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];